fix: remove pre-commit hooks from checklist
seedcase-project/.github pull request #41
Opened 2023-12-20 10:53 UTC by signekb

we will not implement pre-commit hooks after all

2023-12-20 12:09 UTC, K-Beicher submitted a review, later dismissed
Should the 'Build' par of the code section stay, or is that linked with the hooks?

2023-12-22 10:13 UTC, signekb commented
Not entirely sure what is meant by *build* here, actually? :)

2023-12-22 10:32 UTC, lwjohnst86 requested changes

2023-12-22 10:32 UTC, lwjohnst86 commented on .github/PULL_REQUEST_TEMPLATE/pull-request-code.md
> -- [ ] Build and pre-commit hooks have passed locally
I think @K-Beicher meant this build here. I think we could keep this without the precommit text

2023-12-22 11:30 UTC, K-Beicher commented
@lwjohnst86 Talking about this, should I look at making one PR document?  In which case we won't need to remove them here...

2024-01-01 11:32 UTC, lwjohnst86 approved these changes

2024-01-01 11:33 UTC, merged