Feat/copy-relevant-community-files-from-seedcase-project-repo
seedcase-project/.github pull request #6
Opened 2023-10-31 15:50 UTC by signekb

From what I can tell, the files that already exist in the seedcase-project repo that should be move to this repo are: 
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md

Are there others that I might have missed?

2023-11-02 13:31 UTC, signekb commented
@lwjohnst86  CONTRIBUTING links to guide-entries* and Decisions posts**. Should these be moved to this repository as well or should I make changes to the CONTRIBUTING file so it links to these posts in the seedcase-project repo?

*guide entries:  Documentation-Driven Development, How to add posts, and Reviewing through pull requests
**decision posts: Why Discord and Why Quarto

2023-11-04 21:30 UTC, lwjohnst86 requested changes

2023-11-04 21:30 UTC, lwjohnst86 commented on CODE_OF_CONDUCT.md
> +:::
```suggestion
> This is a slightly modified version of the Contributor Covenant Code of
> Conduct (see [attribution](#attribution) below).
```

This callout-note block is a Quarto/HTML thing, so removing from here.

2023-11-04 21:30 UTC, lwjohnst86 commented on CONTRIBUTING.md
> +---
This whole file could be simplified by referring people to read the Community contributing file on the website, since the guides and decisions are generated by Quarto.

2023-11-13 10:29 UTC, signekb commented
@lwjohnst86 I have changed the callout block and simplified the contributing file to only include a reference to the seedcase-project website instead.

2023-11-14 11:06 UTC, lwjohnst86 commented on CONTRIBUTING.md
> +---
```suggestion
# Contributing Guidelines
```

2023-11-14 11:07 UTC, lwjohnst86 approved these changes
Looks great!

2023-11-14 11:07 UTC, merged